/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;
import java.util.ArrayList;
/**
 *
 * @author kieran
 */
public class MainForm extends javax.swing.JFrame {
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContentPane = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addEmployeeMenuItem = new javax.swing.JMenuItem();
        searchAndUpdateEmployeeMenuItem = new javax.swing.JMenuItem();
        searchAndUpdateCustomerMenuItem = new javax.swing.JMenuItem();
        newCustomerMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContentPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/race-car-309123_1280.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel5.setMinimumSize(new java.awt.Dimension(300, 300));
        jLabel5.setPreferredSize(new java.awt.Dimension(300, 300));

        mainContentPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainContentPaneLayout = new javax.swing.GroupLayout(mainContentPane);
        mainContentPane.setLayout(mainContentPaneLayout);
        mainContentPaneLayout.setHorizontalGroup(
            mainContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainContentPaneLayout.createSequentialGroup()
                .addGap(0, 718, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainContentPaneLayout.setVerticalGroup(
            mainContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainContentPaneLayout.createSequentialGroup()
                .addGap(0, 621, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Customer and Employee Management");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N

        addEmployeeMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        addEmployeeMenuItem.setText("Add Employee");
        addEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addEmployeeMenuItem);

        searchAndUpdateEmployeeMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        searchAndUpdateEmployeeMenuItem.setText("Search and Update Employee");
        searchAndUpdateEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAndUpdateEmployeeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(searchAndUpdateEmployeeMenuItem);

        searchAndUpdateCustomerMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        searchAndUpdateCustomerMenuItem.setText("Search and Update Customer");
        searchAndUpdateCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAndUpdateCustomerMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(searchAndUpdateCustomerMenuItem);

        newCustomerMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        newCustomerMenuItem.setText("New Customer Infomation");
        newCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newCustomerMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContentPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContentPane)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchAndUpdateEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAndUpdateEmployeeMenuItemActionPerformed
        // TODO add your handling code here:
        mainContentPane.removeAll();
        SearchAndUpdateEmployeeIFrame updateemployeeframe = new SearchAndUpdateEmployeeIFrame();
        mainContentPane.add(updateemployeeframe);
        updateemployeeframe.setVisible(true);
    }//GEN-LAST:event_searchAndUpdateEmployeeMenuItemActionPerformed

    private void addEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeMenuItemActionPerformed
        // TODO add your handling code here:
        mainContentPane.removeAll();
        AddEmployeeIFrame employeeframe = new AddEmployeeIFrame();
        mainContentPane.add(employeeframe);
        employeeframe.setVisible(true);
    }//GEN-LAST:event_addEmployeeMenuItemActionPerformed

    private void searchAndUpdateCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAndUpdateCustomerMenuItemActionPerformed
        // TODO add your handling code here:
        mainContentPane.removeAll();
        SearchAndUpdateCustomerIFrame updatecustomerframe = new SearchAndUpdateCustomerIFrame();
        mainContentPane.add(updatecustomerframe);
        updatecustomerframe.setVisible(true);
    }//GEN-LAST:event_searchAndUpdateCustomerMenuItemActionPerformed

    private void newCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerMenuItemActionPerformed
        // TODO add your handling code here:
        mainContentPane.removeAll();
        NewCustomerInfomationIFrame newcustomerframe = new NewCustomerInfomationIFrame();
        mainContentPane.add(newcustomerframe);
        newcustomerframe.setVisible(true);
    }//GEN-LAST:event_newCustomerMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEmployeeMenuItem;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mainContentPane;
    private javax.swing.JMenuItem newCustomerMenuItem;
    private javax.swing.JMenuItem searchAndUpdateCustomerMenuItem;
    private javax.swing.JMenuItem searchAndUpdateEmployeeMenuItem;
    // End of variables declaration//GEN-END:variables
}
